name: flutter_book
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^2.0.0  # управление состоянием в приложении
  sqflite: ^2.3.0   # популярная sqlite для работы с данными
  path_provider: ^2.1.1   # для хранения файлов (изображений) контактов
  flutter_slidable: ^3.0.1   # чтобы свайпать контакты при удалении
  intl: ^0.18.1   # для работы с данными времени
  image_picker: ^1.0.6   # плагин для того чтобы достать изображения с устройства
  flutter_calendar_carousel: ^2.4.2  #календарь для списка встреч
  cupertino_icons: ^1.0.2  # мини значки)

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1

flutter:


  uses-material-design: true


